name: Auto Confirm Deposits

on:
  schedule:
    - cron: "*/1 * * * *"      # каждую минуту
  workflow_dispatch: {}

jobs:
  call-edge-func:
    runs-on: ubuntu-latest
    env:
      FUNC_URL: https://einpfuegfsilnoiareco.functions.supabase.co/auto-confirm-deposits
      CALLS: "2"          # 2 раза за запуск
      SLEEP_BETWEEN: "30"  # пауза 30с

    steps:
      - name: Show config
        run: |
          echo "Function URL: $FUNC_URL"
          echo "Calls: $CALLS"
          echo "Sleep between: $SLEEP_BETWEEN"

      - name: Install jq (for pretty logs)
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Loop calls
        run: |
          for i in $(seq 1 "$CALLS"); do
            echo "---- Call #$i ----"
            RESP=$(curl -sS -w '\nHTTP:%{http_code}\n' "$FUNC_URL")
            BODY=$(echo "$RESP" | sed '$d')
            CODE=$(echo "$RESP" | tail -n1 | sed 's/HTTP://')
            echo "Status: $CODE"
            echo "Body:"; echo "$BODY" | jq . || echo "$BODY"

            if [ "$i" -lt "$CALLS" ]; then
              echo "Sleep $SLEEP_BETWEEN sec…"; sleep "$SLEEP_BETWEEN"
            fi
          done
