name: auto-confirm-deposits

on:
  schedule:
    - cron: "* * * * *"   # запуск каждую минуту
  workflow_dispatch:       # возможность запуска вручную из Actions

concurrency:
  group: auto-confirm-deposits
  cancel-in-progress: true

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    env:
      FUNC_URL: https://einpfuegfsilnoiareco.functions.supabase.co/auto-confirm-deposits
      AUTH: ${{ secrets.CRON_KEY }}

    steps:
      - name: Call edge function
        shell: bash
        run: |
          set -euo pipefail
          echo "🔄 Calling $FUNC_URL"
          http_code=$(curl -sS -o /tmp/resp.json -w "%{http_code}" \
            -H "Authorization: Bearer $AUTH" \
            -H "Accept: application/json" \
            "$FUNC_URL")

          echo "HTTP $http_code"
          echo "Response:"
          cat /tmp/resp.json || true

          if [[ "$http_code" -ge 400 ]]; then
            echo "❌ Function returned error"
            exit 1
          fi

          echo "✅ Done"
