name: auto-confirm-deposits

on:
  schedule:
    - cron: "*/1 * * * *"   # каждые 10 минут
  workflow_dispatch:

concurrency:
  group: auto-confirm-deposits
  cancel-in-progress: true

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    env:
      CRON_KEY: ${{ secrets.CRON_KEY }}   # уже есть у вас

    steps:
      - name: Call edge function (retry)
        shell: bash
        run: |
          set -euo pipefail
          FUNC_URL="https://einpfuegfsilnoiareco.functions.supabase.co/auto-confirm-deposits"
          FROM=$(( $(date -u +%s%3N) - 90*60*1000 ))  # окно последних 90 минут
          ATTEMPTS=3
          for i in $(seq 1 $ATTEMPTS); do
            echo "🔄 Attempt $i"
            RESP="$(curl -sS -w '\nHTTP:%{http_code}\n' \
              "${FUNC_URL}?key=${CRON_KEY}&from=${FROM}")" || true
            echo "$RESP"
            CODE="$(echo "$RESP" | tail -n1 | sed 's/HTTP://')"
            [[ "$CODE" == "200" ]] && { echo "✅ OK"; exit 0; }
            [[ $i -lt $ATTEMPTS ]] && { echo "⏳ retry…"; sleep 6; }
          done
          echo "❌ Function returned non-200"; exit 1
